### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'functions'

### ISSUE THREAD

**Issue by tobyhuang78** [ARM-software/devlib#36]
I found one error with the lateset LISA, which has one type error.

in utils/evn.py, one undefined function is called, which is FtraceCikkector, have we missed some patches for it or forget to remove it?

**Comment by cloverpop** [comment]
The root cuase should be that:      Lisa code cloned from https://github.com/ARM-software/lisa.git depends on commit=c5bc987226b3089ac1ea8c45c64b3b5ff1f76695 of https://github.com/ARM-software/devlib.git.   However, if users install devlib in Ubuntu OS via "sudo pip install devlib", that commit is not included yet.

commit c5bc987226b3089ac1ea8c45c64b3b5ff1f76695
Author: Patrick Bellasi <patrick.bellasi@arm.com>
Date:   Tue Jan 26 15:05:58 2016 +0000

    ftrace: add initial support for function profiling

    FTrace allows to collect profiling stats for kernel functions.
    This patch adds the initial support which allows to specify a list of
    kernel function we would like to profile.

    If a list of functions to profile is specified, for each specified function
    we check for that function to be actually one of the available instrumented
    functions which can be monitored by FTrace.
    If a function is not supported, we throw an expection so that the user
    is aware about the analysis which is going to do.

    Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>
