### ISSUE TITLE
Rename TraceCollector

### ISSUE THREAD

**Issue by setrofim** [ARM-software/devlib#378]
As discussed here: https://github.com/ARM-software/devlib/pull/376, "trace" is not an appropriate term for everything that is being collected by `TraceCollector` implementation. Thus, the name is misleading and should be changed. `CollectorBase`, suggested in the same thread, seems reasonable. This will also require corresponding changes to the module name.

**Comment by marcbonnici** [comment]
Implemented with https://github.com/ARM-software/devlib/pull/454
