### ISSUE TITLE
TargetError: No such file or directory

### ISSUE THREAD

**Issue by tobyhuang78** [ARM-software/devlib#38]
STDOUT: /system/bin/sh: cat: /sys/fs/cgroup/devlib_cpuset/big/cpuset.cpus: No such file or directory.

**Comment by tobyhuang78** [comment]
I have checked the target board, there is /sys/fs/cgroup/devlib_cpuset/big/cpus, no cpuset.cpus, it looks like the same issue we have met in Cambridge?

**Comment by setrofim** [comment]
I believe this should have been resolved by https://github.com/ARM-software/devlib/commit/c97618944439c4d71ec4a492dbdf0c83d47c75a3
