### ISSUE TITLE
devlib dependency for lisa

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/devlib#40]
Actually, to use Lisa tool smoothly, we have to upgrade devlib regularly to match the code.
However, if we install devlib/trappy/bart code via "sudo apt install" or "sudo pip install", it may not reflect the latest devlib/trappy/bart code in git repository.

Can we have a generic method to allow lisa tool to manage the devlib/trappy/bart under Lisa's own sub-folders?

**Comment by ep1cman** [comment]
Git submodules would achieve that but they're not perfect:
https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/
