### ISSUE TITLE
host connection does not attempt to check if current user is root

### ISSUE THREAD

**Issue by douglas-raillard-arm** [ARM-software/devlib#404]
Unlike ssh connection, host connection does not check if the username is root, which leads to ask for a sudo password even when the script is already executing as root. What seems to be missing is something like that:
```
# in SshConnection._execute_and_wait_for_prompt()
        if self.username == 'root':
            # As we're already root, there is no need to use sudo.
            as_root = False
```

There is a "unrooted" connection setting, but since it's up to the final user to decide how to run the script, the client code of devlib does not control if the script will be run as root or not, so devlib should probably auto-detect that just like it does for SSH.

**Comment by marcbonnici** [comment]
This should be addressed in https://github.com/ARM-software/devlib/commit/ed135febde0d89e33d2ae0aa014022c9d9324e91. Please re-open if this is not the case.
