### ISSUE TITLE
pr #387 ('su -c') seems to break command execution for me

### ISSUE THREAD

**Issue by v0lker** [ARM-software/devlib#405]
https://github.com/ARM-software/devlib/pull/387 moves from ```echo <command> | su``` to ```su -c <command>```

su doesn't know about the -c option, at least on my test platform with an android q preview, which uses android's own system/extras/su/su.cpp

evil_platform:/ # which su
/system/xbin/su

and that's the only one.. on that machine.

**Comment by marcbonnici** [comment]
Would you be able to provide the version of `su` that you are using and also the error output that attempting to use that parameter produces?

**Comment by v0lker** [comment]
i'm using a different version but visually, it looks like this one: https://android.googlesource.com/platform/system/extras/+/refs/tags/android-q-preview-5/su/su.cpp

the error message is ```su: invalid uid/gid '-c'```

**Comment by marcbonnici** [comment]
A fallback mechanism has been added with https://github.com/ARM-software/devlib/pull/409, would you be able to try this out and see if it resolves your issue?

**Comment by v0lker** [comment]
thanks, that seems to work for me:
```
[ins] In [6]: a = devlib.AndroidTarget(working_directory=s)
[...]
[ins] In [8]: a.execute("whoami")         
Out[8]: 'shell\n'

[ins] In [9]: a.execute("whoami", as_root=True)                                     
Out[9]: 'root\n'
```
