### ISSUE TITLE
Enable post initalisation of modules onto a `Target` 

### ISSUE THREAD

**Issue by marcbonnici** [ARM-software/devlib#412]
Allow the installation of modules to be performed after the initial connection of the `Target` has been created.

**Comment by douglas-raillard-arm** [comment]
@marcbonnici On-demand loading would be very useful in LISA, as we currently load all modules to workaround the limitation. This would reduce the time it takes to connect to a target.

(note: the "on-demand" part can be handled in LISA side if that's something considered too dynamic for something like devlib)
