### ISSUE TITLE
LinuxTarget: Circular dependency installing busybox

### ISSUE THREAD

**Issue by bjackman** [ARM-software/devlib#43]
It's necessary to know the target ABI before installing the busybox binary:
```
self.busybox = self.install(os.path.join(PACKAGE_BIN_DIRECTORY, self.abi, 'busybox'))
```
However we currently require busybox to be installed before we can find the ABI:
```
value = self.execute('{} uname -m'.format(self.busybox)).strip()
```

We should either
 - consider busybox to be a hard dependency (error out in `connect` if `self.get_installed('busybox'` returns None). In this case I guess we'd no longer need to install our own busybox?

-  or find a way to determine the ABI without busybox. My current solution is to try using a native `uname` binary.

**Comment by setrofim** [comment]
Resolved by https://github.com/ARM-software/devlib/commit/5880f6e9efcaf65a35e14a10f482af7510472eb6
