### ISSUE TITLE
Local ping to Android device even when adb_server has been set

### ISSUE THREAD

**Issue by ManubARM** [ARM-software/devlib#468]
Hello,
One of our CI scripts is currently failing when trying to check if an Android device is connected or not. Referring to this file:
https://github.com/ARM-software/devlib/blob/master/devlib/utils/android.py

And considering the following functions:
```
 def __init__(self, device=None, timeout=None, platform=None, adb_server=None,
                 adb_as_root=False):
def adb_connect(device, timeout=None, attempts=MAX_ATTEMPTS):
def _ping(device):
```
By debugging I discovered that even when the the adb_server is set in the __init__(), the  adb_connect() and _ping() function do not "know" the server and try to connect locally.

Is there any particular reason for this?

**Comment by marcbonnici** [comment]
It looks like these functions may be a missing that parameter.
Just to double check your issue, your environment is you have a remote adb server which should be used to connect to the device however it is instead falling back to a local server instance which is therefore failing to connect to the desired device?

On the system if you manually connect to the remote adb server beforehand does this function correctly?

**Comment by ManubARM** [comment]
Yes that is our situation, here is a log:
[check_assets.log](https://github.com/ARM-software/devlib/files/4230648/check_assets.log)

You can find the problem by searching for:
`DEBUG:android:adb -s S2D7N19618010211 shell "ls /data/local/tmp > /dev/null"`

> On the system if you manually connect to the remote adb server beforehand does this function correctly?
If I run the script within the remote server it works. Unfortunately our CI system picks the working agents randomly, and need to use the remote agent with all the phones connected to

**Comment by marcbonnici** [comment]
Thanks for the information. I've submitted a PR to ensure that we're using the supplied  `adb_server` in the adb helper functions:  
https://github.com/ARM-software/devlib/pull/469

Would you be able to pull this and see if it resolves your issue?

**Comment by ManubARM** [comment]
Yes it resolves my issue
Thanks!
