### ISSUE TITLE
energy_probe.py send wrong signal to caiman for ARM energy probe

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/devlib#48]
Hi,

caiman don't register signal handler for SIGTERM but SIGINT, on the other hand energy_probe.py sends signal SIGTERM so eventually caiman don't receive signal and call function sigintHandler().

So I modify devlib code like below, but not sure if it's the correct way; or need change caiman code to handle SIGTERM signal as well.

```
diff --git a/devlib/instrument/energy_probe.py b/devlib/instrument/energy_probe.py
index 54ce8de..232a453 100644
--- a/devlib/instrument/energy_probe.py
+++ b/devlib/instrument/energy_probe.py
@@ -82,7 +82,7 @@ class EnergyProbeInstrument(Instrument):
                                         shell=True)

     def stop(self):
-        os.killpg(self.process.pid, signal.SIGTERM)
+        os.killpg(self.process.pid, signal.SIGINT)

     def get_data(self, outfile):  # pylint: disable=R0914
         all_channels = [c.label for c in self.list_channels()]
```

**Comment by marcbonnici** [comment]
Fixed by https://github.com/ARM-software/devlib/commit/a48775ec5a28c178e0986232f37b8ebb800479ba
