### ISSUE TITLE
Are there any plans to make further releases?

### ISSUE THREAD

**Issue by garethstockwell** [ARM-software/devlib#50]
There are two version tags, both from November 2015 - are there plans to make (and tag) more releases?

**Comment by setrofim** [comment]
We don't have a regular release schedule and, tend to make them on as-needed bases. Since most users seem to install directly from GitHub, there wasn't demand for one for a while.

If there a need for one, we can look into getting a new release out next week.

**Comment by setrofim** [comment]
Version 1.0.0 has now been released.
