### ISSUE TITLE
Remove the dependency on distutils

### ISSUE THREAD

**Issue by setrofim** [ARM-software/devlib#525]
`distutils` is being deprecated (see https://www.python.org/dev/peps/pep-0632/). Any use of `distutils` in `devlib` should be replaced with the equivalent functionality from `setuptools`.

**Comment by douglas-raillard-arm** [comment]
`distutils` will disappear in Python 3.12 which should be released in October 2023:
https://docs.python.org/3.12/whatsnew/3.12.html#removed

> Remove the distutils package. It was deprecated in Python 3.10 by [PEP 632](https://peps.python.org/pep-0632/) “Deprecate distutils module”. For projects still using distutils and cannot be updated to something else, the setuptools project can be installed: it still provides distutils. (Contributed by Victor Stinner in [gh-92584](https://github.com/python/cpython/issues/92584).)

A temporary workaround seems to be adding a runtime dep on setuptools and getting distutils from there
