### ISSUE TITLE
SSH Agent keys

### ISSUE THREAD

**Issue by douglas-raillard-arm** [ARM-software/devlib#574]
Looks like paramiko can handle ssh-agens pretty easily, using: http://docs.paramiko.org/en/stable/api/agent.html

```
        agent = paramiko.Agent()
        agent_keys = agent.get_keys()
        # then iterate over the keys and try to connect with them, until it works or the list is exhausted
```

How should that be exposed in devlib ? I guess it could be a new SSH connection setting.

**Comment by setrofim** [comment]
Connection setting is definitely the way to do it.

**Comment by douglas-raillard-arm** [comment]
Looks like paramiko already uses the SSH agent if no password nor keyfile is given, so we can close this issue
