### ISSUE TITLE
`memoized` tries to hash unhashable tuples

### ISSUE THREAD

**Issue by bjackman** [ARM-software/devlib#60]
In [`__get_memo_id`](https://github.com/ARM-software/devlib/blob/09ec88e9467e8c1569a095898fd089967f0ca52b/devlib/utils/misc.py#L561) we check if objects can be hashed with `isinstance(obj, Hashable)` since 09ec88e9467e8c1569a095898fd089967f0ca52b. 

Unfortunately this breaks for tuples containing unhashable objects (e.g. `({},)`), since they report being an instance of `Hashable` but can't be hashed, resulting in a `TypeError`. Part of me thinks that this is a bug in Python (what's the point in having a `Hashable` type if not all its instances are hashable).  What do you think?

**Comment by setrofim** [comment]
Thanks for reporting the issue. I will investigate.

**Comment by setrofim** [comment]
This should be resolved by https://github.com/ARM-software/devlib/commit/cae239d1dc1d379c3acdec081583a56bf5392313. Please could you confirm that the change fixes the issue for you?

**Comment by bjackman** [comment]
Confirmed fixed :+1:
