### ISSUE TITLE
DeprecationWarning on the pipes module

### ISSUE THREAD

**Issue by douglas-raillard-arm** [ARM-software/devlib#609]
Devlib uses `from pipes import quote` in a number of places. Python 3.11 deprecated the `pipes` modules, and the `quote()` function can be imported from `shlex` module since Python 3.3 (it was probably imported from `pipes` to be compatible with Python 2)

**Comment by marcbonnici** [comment]
Thanks for raising this, we have merged https://github.com/ARM-software/devlib/pull/610 to address the issue.
