### ISSUE TITLE
big/LITTLE cores identification should be based on CPU parts IDs

### ISSUE THREAD

**Issue by derkling** [ARM-software/devlib#7]
In the current version, if not explicitly defined for each platform, devlib assumes that a big.LITTLE target boots using the LITTLE cluster, which affects the naming of CPUs.

For example, if we target a TC2 board which boots using the big cluster:
  
    target = devlib.LinuxTarget(
                           connection_settings = {
                               'username': 'root',
                               'host': '192.168.0.1',
                               'password': u'root'
                           },
                           load_default_modules = False,
                           modules = ['bl'],
                           platform = devlib.platform.arm.TC2())

Than a call to:

    target.little_core

returns 'a15' just because we assume that the label for the first cluster represents a little cpu.

**Comment by setrofim** [comment]
Resolved by https://github.com/ARM-software/devlib/commit/47bf915b7cf3e0e6199d3971a367b302ed058dab
