### ISSUE TITLE
ADB from ANDROID_HOME/platform-tools is not used

### ISSUE THREAD

**Issue by ionela-voinescu** [ARM-software/devlib#80]
Even if the path to ANDROID_HOME is specified, the adb tool from ANDROID_HOME/platform-tools is not used. This can be observed throughout the utils/android.py source code where "adb" is used for all adb commands instead of the global adb variable, that's not even set when the ANDROID_HOME path exists.

**Comment by setrofim** [comment]
Should be resolved by https://github.com/ARM-software/devlib/commit/d5460e1185bdccb08a55d9a21debcfb457d9cd4d

**Comment by ionela-voinescu** [comment]
Awesome! Thank you!
