### ISSUE TITLE
cpufreq: set_X_for_cpus doesnt do as expected

### ISSUE THREAD

**Issue by mcgeagh** [ARM-software/devlib#98]
set_governor_for_cpus and set_frequency_for_cpus both have a parameter called 'cpus' and its description states:
:param cpus: The list of CPU for which the [governor|frequency] is to be set.

However neither function ever use this parameter.
Instead, it gets its list of cpus to perform this action onto based on self.target.list_online_cpus()

**Comment by marcbonnici** [comment]
This should be fixed by commit b444ae65c91cf5664f7c5e22def171c9c4476ac5
